GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZUBleGFtcGxlLmNvbSIsIm5iZiI6MTYwNjQ3NjQ3OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Im1uLWpkYmMtYXV0aCIsImxhbmd1YWdlIjoiZW4iLCJoYWlyQ29sb3IiOiJicm93biIsImV4cCI6MTYwNjQ4MDA3OCwiaWF0IjoxNjA2NDc2NDc4fQ.V_8YF5t27qQe44pR3DmQfyRdpw3gX6PrV6ghmGOp-cA
