micronaut:
  application:
    name: mn-stock-broker
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: some-pretty-long-secret-for-2020
    # With that the static routes are available without auth
    reject-not-found: false
#json settings
jackson:
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  generator:
    # writeNumbersAsString: true
    # writeBigDecimalAsPlain: true
  deserialization:
    failOnUnknownProperties: false
# app settings
hello:
  controller:
    path: '/hello'
  service:
    greeting: 'Hello from service'
  config:
    greeting:
      de: 'Hallo!'
      en: 'Hello!'

